---
- hosts: localhost
  vars:
    container_cli: 'podman'
  vars_files:
    - vars/defaults.yaml
  tasks:
    - import_tasks: common_tasks.yaml

    - name: 'Tag images'
      command: "{{ container_cli }} tag {{ item.value.image_name }}:{{ item.value.tag }} {{ registry }}/{{ project }}/{{ item.value.image_name }}:{{ item.value.tag }}"
      with_dict: "{{ images }}"

    - name: 'Push images'
      command: "{{ container_cli }} push {{ registry }}/{{ project }}/{{ item.value.image_name }}:{{ item.value.tag }}"
      with_dict: "{{ images }}"
